### ISSUE TITLE
Generate new documentation

### ISSUE THREAD

**Issue by arslanbekov** [OpenVPN/terraform-provider-openvpn-cloud#17]
There is a problem generating new documentation

**Comment by vladimir-kozyrev** [comment]
The existing documentation can be confusing because of the difference in the resource names.
The correct name for this case if `openvpncloud_user` and not `openvpn-cloud_user`.
<img width="849" alt="image" src="https://user-images.githubusercontent.com/7099677/227876248-a35538ba-945a-4b74-8296-6ba9a437ef53.png">

**Comment by vladimir-kozyrev** [comment]
This link can be helpful https://developer.hashicorp.com/terraform/registry/providers/docs

**Comment by sahaqaa** [comment]
We've published new version of Terraform Provider to Registry: https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest

Going forward only https://registry.terraform.io/providers/OpenVPN/cloudconnexa/latest will be developed.

Please give new provider a try, hopefully it will fix your issue.

In case if problem persists - please open new "Issue" (https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues)

Sorry for inconvenience.
